install: true
language: scala
scala:
  - 2.11.2
notifications:
  slack:
    secure: h0QcxCkN1aYhEgEvrLi9eKM2OdVOSfnPkQfwCXspV5fDYyEh96rDDJ4kBWoW6M0Fp4Uq7TZY6tGzUAdbnTU/Yg2+T0+H4+lDsfPhPTmmeZkAaByXVN2gOrNft06yHvte7WaDfON1eIUweNvuP8RGSgzyMpgAgIfhu5L43an7m/c=
